name: PR test

on:
  pull_request:

jobs:
  build1:
    uses: ndechesne/github-actions-tests/.github/workflows/build.yml@master
    with:
      src: my-source
      branch: main
  build2:
    uses: ndechesne/github-actions-tests/.github/workflows/build.yml@master
    with:
      dst: my-destination
      branch: test
  build3:
    uses: ndechesne/github-actions-tests/.github/workflows/build.yml@master
    with:
      src: my-source
      dst: my-destination
      branch: dev


